create schema if not exists extensions;
create extension if not exists postgis with schema extensions;

create table public.cameras (
  id integer generated by default as identity primary key,
  camera_id text not null unique,
  name text,
  department text,
  department_full text,
  ownership text default 'Government',
  city text,
  site text,
  lat double precision,
  lng double precision,
  coords_approx boolean default false,
  camera_type text,
  resolution text,
  make text,
  model text,
  protocol text,
  vms_platform text,
  stream_url text,
  codec text,
  container text,
  delivery text,
  storage_type text,
  retention_days integer,
  connectivity text,
  health_status text,
  amc_expiry text,
  analytics_enabled boolean default false,
  source text,
  dept_inferred boolean default false,
  geom extensions.geography(point, 4326)
);

create index cameras_camera_id_idx on public.cameras (camera_id);
create index cameras_department_idx on public.cameras (department);
create index cameras_city_idx on public.cameras (city);
create index cameras_camera_type_idx on public.cameras (camera_type);
create index cameras_health_status_idx on public.cameras (health_status);
create index cameras_geom_gix on public.cameras using gist (geom);

create table public.detection_events (
  id integer generated by default as identity primary key,
  camera_id text,
  camera_name text,
  city text,
  event_type text,
  plate text,
  plate_norm text,
  vehicle_type text,
  color text,
  confidence double precision,
  plate_confidence double precision,
  snapshot text,
  lat double precision,
  lng double precision,
  ts timestamptz default now()
);

create index detection_events_camera_id_idx on public.detection_events (camera_id);
create index detection_events_city_idx on public.detection_events (city);
create index detection_events_event_type_idx on public.detection_events (event_type);
create index detection_events_plate_idx on public.detection_events (plate);
create index detection_events_plate_norm_idx on public.detection_events (plate_norm);
create index detection_events_color_idx on public.detection_events (color);
create index detection_events_ts_idx on public.detection_events (ts);

create table public.watchlist (
  id integer generated by default as identity primary key,
  category text,
  label text,
  kind text,
  plate_norm text,
  vehicle_type text,
  color text,
  case_ref text,
  reason text,
  source text default 'Representative dataset',
  severity text default 'high',
  active boolean default true,
  created timestamptz default now()
);

create index watchlist_category_idx on public.watchlist (category);
create index watchlist_plate_norm_idx on public.watchlist (plate_norm);

create table public.alerts (
  id integer generated by default as identity primary key,
  kind text,
  watchlist_id integer,
  watchlist_category text,
  case_ref text,
  matched_on text,
  detection_id integer,
  vehicle_count integer,
  camera_id text,
  camera_name text,
  city text,
  lat double precision,
  lng double precision,
  plate text,
  vehicle_type text,
  color text,
  reason text,
  source text,
  severity text default 'high',
  snapshot text,
  acknowledged boolean default false,
  ts timestamptz default now()
);

create index alerts_kind_idx on public.alerts (kind);
create index alerts_watchlist_id_idx on public.alerts (watchlist_id);
create index alerts_camera_id_idx on public.alerts (camera_id);
create index alerts_ts_idx on public.alerts (ts);

create table public.audit_log (
  id integer generated by default as identity primary key,
  "user" text,
  role text,
  action text,
  detail text,
  ts timestamptz default now()
);

create index audit_log_user_idx on public.audit_log ("user");
create index audit_log_action_idx on public.audit_log (action);
create index audit_log_ts_idx on public.audit_log (ts);

alter table public.cameras enable row level security;
alter table public.detection_events enable row level security;
alter table public.watchlist enable row level security;
alter table public.alerts enable row level security;
alter table public.audit_log enable row level security;

comment on schema public is
  'Netra application tables are accessed only through the FastAPI backend.';
